### ISSUE TITLE
readme.md clarification

### ISSUE THREAD

**Issue by nagtegaal** [fredrikpersson92/minihass#10]
```
  lovelace:
    mode: yaml
    resources:
    - url: /www/community/button-card/button-card.js
      type: module
    - url: https://fonts.googleapis.com/css2?family=Montserrat:wght@300;700&display=swap"
      type: css
``` 
This goes into configuration.yaml, right? readme.md doesn't state that very clearly, as the sentence is being cut of here:
```
To incorporate the button-card and the selected font, insert the following into your
```
